### ISSUE TITLE
Project won't build

### ISSUE THREAD

**Issue by goodmove** [florianingerl/com.florianingerl.util.regex#2] opened 2017-03-09 14:18 UTC
Fix build.xml file for successful build with ant.
`classname` attribute should look like this:
![image](https://cloud.githubusercontent.com/assets/10362721/23753946/de76ad8e-050d-11e7-8c0e-056e6c7090d9.png)

**Comment by florianingerl** [comment] 2017-04-09 13:08
Thanks a lot. The problem is now fixed.

**Closed as completed by florianingerl** 2017-04-09 13:08 UTC
